ServerName %{HTTP_HOST}

<VirtualHost *:80>
    DocumentRoot /app/data/current/public
    DirectoryIndex index.php
    SetEnv APP_ENV production

    LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" proxy
    CustomLog "|/bin/cat" proxy
    ErrorLog "|/bin/cat"

    SetEnvIf X-Forwarded-Proto "^https$" HTTPS=on

    RewriteEngine On
    RewriteRule ^/storage/pet-profiles(?:/|$) - [R=404,L,NC]

    <Directory /app/data/current/public>
        Options +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    Include "/app/code/apache/rpaf.conf"
    Include "/app/code/apache/phpmyadmin.conf"
</VirtualHost>
